import '@/app/globals.css';
import type { Metadata } from 'next';
import { Heebo, Inter } from 'next/font/google';
import Header from "@/components/header";
import React from "react";

const inter = Inter({
  subsets: ['latin'],
})
const heebo = Heebo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <header className="w-full z-10 border-color shadow-md justify-center dark:shadow-gray-800 lg:flex">
          <Header />
        </header>
        <main className="flex justify-center">
          {children}
        </main>
      </body>
    </html>
  )
}
