import '@/app/globals.css'
import type { Metadata } from 'next'
import { Heebo, Noto_Serif } from 'next/font/google'

const notoSerif = Noto_Serif({ subsets: ['latin'] })
const heebo = Heebo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heebo.className}>{children}</body>
    </html>
  )
}
