import '@/app/globals.css';
import type { Metadata } from 'next';
import { Heebo, Noto_Serif } from 'next/font/google';
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";
import {getFilesByExtension} from "@/lib/filesystem";

const notoSerif = Noto_Serif({ subsets: ['latin'] });
const heebo = Heebo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <header className="w-full z-10 border-color shadow-md justify-center dark:shadow-gray-800 lg:flex">
          <Header />
        </header>
        {children}
      </body>
    </html>
  )
}
